export interface IContent {
  tags: string[],
  owner: {
    account_id: number,
    reputation: number,
    user_id: number,
    user_type: string,
    profile_image: string,
    display_name: string,
    link: string,
  },
  is_answered: boolean,
  view_count: number,
  answer_count: number,
  score: number,
  last_activity_date: Date,
  creation_date: Date,
  last_edit_date: Date,
  question_id: number,
  content_license: string,
  link: string,
  title: string,
};

export interface IUser {
  badge_counts: {
    bronze: number,
    silver: number,
    gold: number,
  },
  account_id: number,
  is_employee: boolean,
  last_access_date: Date,
  reputation_change_year: number,
  reputation_change_quarter: number,
  reputation_change_month: number,
  reputation_change_week: number,
  reputation_change_day: number,
  reputation: number,
  creation_date: number,
  user_type: string,
  user_id: number,
  location: string,
  link: string,
  profile_image: string,
  display_name: string,
}